# Generated by Django 4.0.1 on 2022-03-14 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField(blank=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'Mężczyzna'), ('f', 'Kobieta')], max_length=1)),
                ('photo', models.ImageField(default='default.png', upload_to='photos/')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('last_seen', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reporting_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
