# Generated by Django 4.0.1 on 2022-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='age',
            field=models.SmallIntegerField(blank=True, verbose_name='Wiek'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
