# Generated by Django 4.0.1 on 2022-03-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_missingperson_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Imie'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=1, verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_seen',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ostatnio widziany'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='photos/', verbose_name='Zdjęcie'),
        ),
    ]
